{{- if .Values.imagePullSecrets.enabled -}}
{{- range .Values.imagePullSecrets.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ include "openchoreo-service.namespace" $ }}
  labels:
    {{- include "openchoreo-service.labels" $ | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .secretStore.name }}
    kind: {{ .secretStore.kind }}
  target:
    name: {{ .name }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ `{{ .dockerconfigjson }}` }}"
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: {{ .remoteRef.key }}
{{- end }}
{{- end }}
