{{- if .Values.openchoreo.workload.endpoints -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openchoreo-service.fullname" . }}
  namespace: {{ include "openchoreo-service.namespace" . }}
  labels:
    {{- include "openchoreo-service.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
  selector:
    {{- include "openchoreo-service.selectorLabels" . | nindent 4 }}
  ports:
    {{- include "openchoreo-service.servicePorts" . | nindent 4 }}
{{- end }}
